# Update minicloud
os: linux
dist: focal
sudo: required
language: minimal

# Install Hugo
install:
  - sudo snap install hugo --channel=extended

script:
  - git submodule update --remote static/minicloud
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  on:
branch: master
